require("corsixth")
require("class_test_base")

require("queue")

local Queue = _G["Queue"]

local function makePatient()
  return {
    is_emergency = false,
    getRoom = function() return nil end,
    hospital = {
      hosp_cheats = {isCheatActive = function() return false end},
    },
    getAttribute = function() return 1 end,
    setMood = function() end,
  }
end

describe("queue.lua: Door/room queue management", function()
  local queue

  before_each(function()
    queue = Queue()
  end)

  describe("Constructor", function()
    it("initializes with default values", function()
      assert.are.equal(0, queue:size())
      assert.are.equal(0, queue:reportedSize())
      assert.are.equal(0, queue:expectedSize())
      assert.are.equal(6, queue.max_size)
      assert.are.equal(0, queue.bench_threshold)
    end)

    it("initializes empty expected table", function()
      assert.are.same({}, queue.expected)
      assert.are.equal(0, queue.expected_count)
    end)
  end)

  describe("push/pop", function()
    it("pushes humanoid to queue", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(1, queue:size())
    end)

    it("pop removes and returns front humanoid", function()
      local p = makePatient()
      queue:push(p)
      local popped = queue:pop()
      assert.are.equal(p, popped)
      assert.are.equal(0, queue:size())
    end)

    it("front returns first without removing", function()
      local p = makePatient()
      queue:push(p)
      local front = queue:front()
      assert.are.equal(p, front)
      assert.are.equal(1, queue:size())
    end)

    it("pop decrements reported_size when full", function()
      local p = makePatient()
      queue:push(p)
      queue:pop()
      assert.are.equal(0, queue:reportedSize())
    end)
  end)

  describe("Queue size methods", function()
    it("size returns total humanoids", function()
      queue:push(makePatient())
      queue:push(makePatient())
      assert.are.equal(2, queue:size())
    end)

    it("reportedSize tracks displayable patients", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(1, queue:reportedSize())
    end)

    it("isFull checks against max_size", function()
      for i = 1, 6 do queue:push(makePatient()) end
      assert.is_true(queue:isFull())
    end)
  end)

  describe("Priority ordering", function()
    it("emergency patients (priority 4) before regular patients (6)", function()
      local regular = makePatient()
      local emergency = makePatient()
      emergency.is_emergency = true
      queue:push(regular)
      queue:push(emergency)
      assert.are.equal(emergency, queue:front())
    end)
  end)

  describe("Queue size/empty", function()
    it("size returns 0 for empty queue", function()
      assert.are.equal(0, queue:size())
    end)

    it("isFull false for empty queue", function()
      assert.is_false(queue:isFull())
    end)

    it("reportedSize 0 for empty", function()
      assert.are.equal(0, queue:reportedSize())
    end)
  end)

  describe("Max size management", function()
    it("decreaseMaxSize reduces max_size", function()
      queue:decreaseMaxSize(2)
      assert.are.equal(4, queue.max_size)
    end)

    it("decreaseMaxSize floors at 0", function()
      queue:decreaseMaxSize(10)
      assert.are.equal(0, queue.max_size)
    end)

    it("increaseMaxSize increases max_size", function()
      queue:increaseMaxSize(4)
      assert.are.equal(10, queue.max_size)
    end)

    it("increaseMaxSize caps at 30", function()
      queue:increaseMaxSize(100)
      assert.are.equal(30, queue.max_size)
    end)

    it("setMaxQueue sets exact value", function()
      queue:setMaxQueue(12)
      assert.are.equal(12, queue.max_size)
    end)

    it("decreaseMaxSize floors at 0", function()
      queue:decreaseMaxSize(100)
      assert.are.equal(0, queue.max_size)
    end)

    it("increaseMaxSize caps at 30", function()
      queue:increaseMaxSize(100)
      assert.are.equal(30, queue.max_size)
    end)

    it("setBenchThreshold sets threshold", function()
      queue:setBenchThreshold(5)
      assert.are.equal(5, queue.bench_threshold)
    end)

    it("setMaxQueue sets exact value", function()
      queue:setMaxQueue(15)
      assert.are.equal(15, queue.max_size)
    end)
  end)

  describe("Emergency detection", function()
    it("hasEmergencyPatient detects emergency flag", function()
      local p = makePatient()
      p.is_emergency = true
      queue:push(p)
      assert.is_true(queue:hasEmergencyPatient())
    end)

    it("hasEmergencyPatient false when none", function()
      queue:push(makePatient())
      assert.is_false(queue:hasEmergencyPatient())
    end)
  end)

  describe("Queue manipulation", function()
    it("front returns first without removing", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(p, queue:front())
      assert.are.equal(1, queue:size())
    end)

    it("back returns last", function()
      local p1 = makePatient()
      local p2 = makePatient()
      queue:push(p1)
      queue:push(p2)
      assert.are.equal(p2, queue:back())
    end)

    it("removeValue returns true if found", function()
      local p = makePatient()
      queue:push(p)
      assert.is_true(queue:removeValue(p))
      assert.are.equal(0, queue:size())
    end)

    it("removeValue false when not found", function()
      assert.is_false(queue:removeValue({}))
    end)

    it("move shifts positions", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:move(3, 1)
      assert.are.equal(p3, queue:front())
    end)

    it("movePatient works with relative indices", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:movePatient(2, "front")
      local front_patient = queue:reportedHumanoid(1)
      assert.are.equal(p2, front_patient)
    end)

    it("remove by index", function()
      local p = makePatient()
      queue:push(p)
      local removed = queue:remove(1)
      assert.are.equal(p, removed)
      assert.are.equal(0, queue:size())
    end)
  end)

  describe("Max size bounds", function()
    it("decreaseMaxSize floors at 0", function()
      queue:decreaseMaxSize(100)
      assert.are.equal(0, queue.max_size)
    end)

    it("increaseMaxSize caps at 30", function()
      queue:increaseMaxSize(100)
      assert.are.equal(30, queue.max_size)
    end)

    it("setBenchThreshold sets threshold", function()
      queue:setBenchThreshold(5)
      assert.are.equal(5, queue.bench_threshold)
    end)

    it("setMaxQueue sets exact value", function()
      queue:setMaxQueue(15)
      assert.are.equal(15, queue.max_size)
    end)
  end)

  describe("Emergency detection", function()
    it("hasEmergencyPatient detects emergency flag", function()
      local p = makePatient()
      p.is_emergency = true
      queue:push(p)
      assert.is_true(queue:hasEmergencyPatient())
    end)

    it("hasEmergencyPatient false when none", function()
      queue:push(makePatient())
      assert.is_false(queue:hasEmergencyPatient())
    end)
  end)

  describe("Queue manipulation", function()
    it("front returns first without removing", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(p, queue:front())
      assert.are.equal(1, queue:size())
    end)

    it("back returns last", function()
      local p1 = makePatient()
      local p2 = makePatient()
      queue:push(p1)
      queue:push(p2)
      assert.are.equal(p2, queue:back())
    end)

    it("removeValue returns true if found", function()
      local p = makePatient()
      queue:push(p)
      assert.is_true(queue:removeValue(p))
      assert.are.equal(0, queue:size())
    end)

    it("removeValue false when not found", function()
      assert.is_false(queue:removeValue({}))
    end)

    it("move shifts positions", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:move(3, 1)
      assert.are.equal(p3, queue:front())
    end)

    it("movePatient works with relative indices", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:movePatient(2, "front")
      local front_patient = queue:reportedHumanoid(1)
      assert.are.equal(p2, front_patient)
    end)

    it("remove by index", function()
      local p = makePatient()
      queue:push(p)
      local removed = queue:remove(1)
      assert.are.equal(p, removed)
      assert.are.equal(0, queue:size())
    end)
  end)

  describe("Max size bounds", function()
    it("decreaseMaxSize floors at 0", function()
      queue:decreaseMaxSize(100)
      assert.are.equal(0, queue.max_size)
    end)

    it("increaseMaxSize caps at 30", function()
      queue:increaseMaxSize(100)
      assert.are.equal(30, queue.max_size)
    end)

    it("setBenchThreshold sets threshold", function()
      queue:setBenchThreshold(5)
      assert.are.equal(5, queue.bench_threshold)
    end)

    it("setMaxQueue sets exact value", function()
      queue:setMaxQueue(15)
      assert.are.equal(15, queue.max_size)
    end)
  end)

  describe("Emergency detection", function()
    it("hasEmergencyPatient detects emergency flag", function()
      local p = makePatient()
      p.is_emergency = true
      queue:push(p)
      assert.is_true(queue:hasEmergencyPatient())
    end)

    it("hasEmergencyPatient false when none", function()
      queue:push(makePatient())
      assert.is_false(queue:hasEmergencyPatient())
    end)
  end)

  describe("Queue manipulation", function()
    it("front returns first without removing", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(p, queue:front())
      assert.are.equal(1, queue:size())
    end)

    it("back returns last", function()
      local p1 = makePatient()
      local p2 = makePatient()
      queue:push(p1)
      queue:push(p2)
      assert.are.equal(p2, queue:back())
    end)

    it("removeValue returns true if found", function()
      local p = makePatient()
      queue:push(p)
      assert.is_true(queue:removeValue(p))
      assert.are.equal(0, queue:size())
    end)

    it("removeValue false when not found", function()
      assert.is_false(queue:removeValue({}))
    end)

    it("move shifts positions", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:move(3, 1)
      assert.are.equal(p3, queue:front())
    end)

    it("movePatient works with relative indices", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:movePatient(2, "front")
      local front_patient = queue:reportedHumanoid(1)
      assert.are.equal(p2, front_patient)
    end)

    it("remove by index", function()
      local p = makePatient()
      queue:push(p)
      local removed = queue:remove(1)
      assert.are.equal(p, removed)
      assert.are.equal(0, queue:size())
    end)
  end)

  describe("Max size bounds", function()
    it("decreaseMaxSize floors at 0", function()
      queue:decreaseMaxSize(100)
      assert.are.equal(0, queue.max_size)
    end)

    it("increaseMaxSize caps at 30", function()
      queue:increaseMaxSize(100)
      assert.are.equal(30, queue.max_size)
    end)

    it("setBenchThreshold sets threshold", function()
      queue:setBenchThreshold(5)
      assert.are.equal(5, queue.bench_threshold)
    end)

    it("setMaxQueue sets exact value", function()
      queue:setMaxQueue(15)
      assert.are.equal(15, queue.max_size)
    end)
  end)

  describe("Emergency detection", function()
    it("hasEmergencyPatient detects emergency flag", function()
      local p = makePatient()
      p.is_emergency = true
      queue:push(p)
      assert.is_true(queue:hasEmergencyPatient())
    end)

    it("hasEmergencyPatient false when none", function()
      queue:push(makePatient())
      assert.is_false(queue:hasEmergencyPatient())
    end)
  end)

  describe("Queue manipulation", function()
    it("front returns first without removing", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(p, queue:front())
      assert.are.equal(1, queue:size())
    end)

    it("back returns last", function()
      local p1 = makePatient()
      local p2 = makePatient()
      queue:push(p1)
      queue:push(p2)
      assert.are.equal(p2, queue:back())
    end)

    it("removeValue returns true if found", function()
      local p = makePatient()
      queue:push(p)
      assert.is_true(queue:removeValue(p))
      assert.are.equal(0, queue:size())
    end)

    it("removeValue false when not found", function()
      assert.is_false(queue:removeValue({}))
    end)

    it("move shifts positions", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:move(3, 1)
      assert.are.equal(p3, queue:front())
    end)

    it("movePatient works with relative indices", function()
      local p1 = makePatient()
      local p2 = makePatient()
      local p3 = makePatient()
      queue:push(p1)
      queue:push(p2)
      queue:push(p3)
      queue:movePatient(2, "front")
      local front_patient = queue:reportedHumanoid(1)
      assert.are.equal(p2, front_patient)
    end)

    it("remove by index", function()
      local p = makePatient()
      queue:push(p)
      local removed = queue:remove(1)
      assert.are.equal(p, removed)
      assert.are.equal(0, queue:size())
    end)
  end)

  describe("Max size bounds", function()
    it("decreaseMaxSize floors at 0", function()
      queue:decreaseMaxSize(100)
      assert.are.equal(0, queue.max_size)
    end)

    it("increaseMaxSize caps at 30", function()
      queue:increaseMaxSize(100)
      assert.are.equal(30, queue.max_size)
    end)

    it("setBenchThreshold sets threshold", function()
      queue:setBenchThreshold(5)
      assert.are.equal(5, queue.bench_threshold)
    end)

    it("setMaxQueue sets exact value", function()
      queue:setMaxQueue(15)
      assert.are.equal(15, queue.max_size)
    end)
  end)

  describe("Emergency detection", function()
    it("hasEmergencyPatient detects emergency flag", function()
      local p = makePatient()
      p.is_emergency = true
      queue:push(p)
      assert.is_true(queue:hasEmergencyPatient())
    end)

    it("hasEmergencyPatient false when none", function()
      queue:push(makePatient())
      assert.is_false(queue:hasEmergencyPatient())
    end)
  end)

  describe("reportedHumanoid", function()
    it("returns patient by index", function()
      local p = makePatient()
      queue:push(p)
      assert.are.equal(p, queue:reportedHumanoid(1))
    end)
  end)
end)

local function makePatient()
  return {
    is_emergency = false,
    getRoom = function() return nil end,
    hospital = {hosp_cheats = {isCheatActive = function() return false end}},
    getAttribute = function() return 1 end,
    setMood = function() end,
  }
end
